### ISSUE TITLE
nächster stream

### ISSUE THREAD

**Issue by seriousm4x** [wubbl0rz/SpeedChamp#9]
![](https://cdn.betterttv.net/emote/610c5aeb76ea4e2b9f75950a/3x)

**Comment by wubbl0rz** [comment]
![](https://camo.githubusercontent.com/0072020269ccf97a0192109422ab61bf99084532c15ea41cc67519b7f8613505/68747470733a2f2f63646e2e6265747465727474762e6e65742f656d6f74652f3631306335616562373665613465326239663735393530612f3378)

**Comment by noel-lang** [comment]
![](https://camo.githubusercontent.com/0072020269ccf97a0192109422ab61bf99084532c15ea41cc67519b7f8613505/68747470733a2f2f63646e2e6265747465727474762e6e65742f656d6f74652f3631306335616562373665613465326239663735393530612f3378)

**Comment by seriousm4x** [comment]
![](https://cdn.frankerfacez.com/emoticon/425196/4)
